### PR TITLE
Fix CI build (locally, at least)

### PR DESCRIPTION
**Pull request by lbraun**

### CODE REVIEW

**Comment by lbraun** [comment]
@yakloinsteak would you be willing to help me fix the Puma config scheme here like you did in DE?

**Comment by yakloinsteak** [comment]
Sure. I'm not exactly sure what you need, though. Are you talking about the capistrano task to restart puma?

**Comment by lbraun** [comment]
Ah no sorry, that wasn't very clear at all was it? 🥟 

I mean the changes needed when we upgrade puma from 5.5 to 5.6-- I believe in DE you said that just required a quick change to the puma config?

**Comment by yakloinsteak** [comment]
I can help with that. The config is very different here, but I can definitely make sure it won't break when we deploy next. When do you need it by? I'll need root access, so hopefully somebody has aaron's sudo pass or we can get root some other way.

**Comment by lbraun** [comment]
Ok thanks. Let me check with Derrish. I'm not sure what the priority is on WRI maintenance. I have Aaron's sudo password.

**Pull request merged**
