### PR TITLE
Make minor changes

### PR DESCRIPTION
**Pull request by ZachCMP**
Makes these changes in #215:

-  Add link to News & Publications page
-  Move News & Publications section between first paragraph and Tool Dock
-  Adjust home page copy
-  Add Read More link after first paragraph
-  Remove 1-5 footer

### CODE REVIEW

**Review by lbraun — APPROVED** [review]
💯

**Review by lbraun — COMMENTED** [review]
Issue says "Delete the 2nd and 3rd text paragraphs," but I only see one paragraph deleted here?

**Comment by ZachCMP** [comment]
@lbraun I just followed the mocks, which only has the first paragraph and the news paragraph.  I'm not sure exactly what content was deleted to get there.  It may have only been one paragraph, but regardless it matches the mocks now.

**Comment by lbraun** [comment]
Sounds good 🤷‍♂️  Thanks!

**Pull request merged**
